# Generated by Django 5.0.1 on 2024-02-18 10:45

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('facultyPanel', '0004_remove_program_student'),
        ('studentPanel', '0006_rename_qualification_student_degree_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='student',
            name='program_name',
        ),
        migrations.AddField(
            model_name='student',
            name='program',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='facultyPanel.program'),
        ),
        migrations.AlterField(
            model_name='student',
            name='admission_category',
            field=models.CharField(max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='student',
            name='degree',
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='student',
            name='roll_no',
            field=models.CharField(max_length=50, null=True),
        ),
    ]
