# Generated by Django 5.0.1 on 2024-02-18 10:18

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('facultyPanel', '0002_alter_faculty_person'),
        ('studentPanel', '0006_rename_qualification_student_degree_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Program',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('program_name', models.CharField(max_length=100)),
                ('departmentID', models.DecimalField(decimal_places=2, max_digits=10)),
                ('program_duration', models.FloatField()),
                ('student', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='studentPanel.student')),
            ],
        ),
        migrations.CreateModel(
            name='exam',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('examid', models.CharField(max_length=100)),
                ('exam_type', models.CharField(max_length=100)),
                ('start_date', models.DateField()),
                ('end_date', models.DateField()),
                ('duration', models.DurationField()),
                ('program_name', models.CharField(max_length=100)),
                ('totalmarks', models.DecimalField(decimal_places=2, max_digits=10)),
                ('passingmark', models.DecimalField(decimal_places=2, max_digits=10)),
                ('semester', models.DecimalField(decimal_places=2, max_digits=10)),
                ('program', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='facultyPanel.program')),
            ],
        ),
    ]
