# Generated by Django 5.0.1 on 2024-02-18 10:45

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('facultyPanel', '0003_program_exam'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='program',
            name='student',
        ),
    ]
