# Generated by Django 5.0.1 on 2024-02-18 11:05

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('facultyPanel', '0004_remove_program_student'),
    ]

    operations = [
        migrations.CreateModel(
            name='ExamPaper',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('paperid', models.IntegerField(max_length=10)),
                ('exam', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='facultyPanel.exam')),
                ('faculty', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='facultyPanel.faculty')),
            ],
        ),
        migrations.CreateModel(
            name='Subject',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('subjectcode', models.CharField(max_length=20)),
                ('subjectname', models.CharField(max_length=20)),
                ('departmentid', models.IntegerField(max_length=10)),
                ('refrencebook', models.CharField(max_length=20)),
                ('programename', models.ManyToManyField(to='facultyPanel.program')),
            ],
        ),
    ]
