# Generated by Django 5.0.1 on 2024-02-18 11:47

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('facultyPanel', '0005_exampaper_subject'),
    ]

    operations = [
        migrations.RenameField(
            model_name='subject',
            old_name='programename',
            new_name='programe',
        ),
    ]
