# Generated by Django 5.0.1 on 2024-02-18 18:27

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('facultyPanel', '0007_hallticket'),
        ('managementPanel', '0002_hod_userid'),
        ('studentPanel', '0007_remove_student_program_name_student_program_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Club',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('clubid', models.IntegerField()),
                ('clubname', models.CharField(max_length=100)),
                ('estdate', models.DateField()),
                ('type', models.CharField(max_length=100)),
                ('faculty', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='facultyPanel.faculty')),
                ('hod', models.ManyToManyField(to='managementPanel.hod')),
                ('student', models.ManyToManyField(to='studentPanel.student')),
            ],
        ),
        migrations.CreateModel(
            name='Event',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('eventID', models.IntegerField()),
                ('eventname', models.CharField(max_length=100)),
                ('description', models.TextField()),
                ('starttime', models.DateField()),
                ('duration', models.DurationField()),
                ('hod', models.ManyToManyField(to='managementPanel.hod')),
            ],
        ),
    ]
